settings:
  home-permissions:
    1: 'sleepyhomes.set.1'
    2: 'sleepyhomes.set.2'
    3: 'sleepyhomes.set.3'
    4: 'sleepyhomes.set.4'
    5: 'sleepyhomes.set.5'
    6: 'sleepyhomes.set.6'
    7: 'sleepyhomes.set.7'
  rows: 4
  teleport-delay: 5
  homes-slots:
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
  dyes-slots:
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
menu-titles:
  main-homes: '&8Homes'
  edit-home: '&8Delete Home #%number%'
items:
  bed-empty:
    material: GRAY_BED
    name: '&7No Home'
    lore:
      - '&7Click the dye below to set this home.'
  bed-set:
    material: LIGHT_BLUE_BED
    name: '&bHome #%number%'
    lore:
      - '&7Click to teleport.'
  dye-empty:
    material: GRAY_DYE
    name: '&7Set Home #%number%'
    lore:
      - '&7Click to set your home here.'
  dye-set:
    material: LIGHT_BLUE_DYE
    name: '&bEdit Home #%number%'
    lore:
      - '&7Click to open edit menu.'
  edit-menu:
    back-slot: 11 
    delete-slot: 15 
    back:
      material: RED_STAINED_GLASS_PANE
      name: '&cɢᴏ ʙᴀᴄᴋ'
      lore: []
    delete:
      material: GREEN_STAINED_GLASS_PANE
      name: '&aᴅᴇʟᴇᴛᴇ ʜᴏᴍᴇ'
      lore: []

messages:
  no-permission: '&cYou don''t have permission to set home'
  home-set: '#2CFF00Home #%number% has been set.'
  home-deleted: '#ff0000Home #%number% has been deleted.'
  teleporting: '&7Teleporting in #0099FF%seconds% &7second(s)'
  no-home: '#ff0000The home has not been set!'
  invalid-home: '#ff0000You must select a valid home.'
  config-reloaded: '#2CFF00Configuration reloaded successfully!'
