name: SleepyHomes
main: me.yourname.sleepyhomes.SleepyHomes
version: '1.0.0'
api-version: '1.21'
description: A GUI-based home management plugin with set, teleport, delete, and reload features.
authors:
  - SleepyStudios
website: https://discord.gg/AQ4YgRYzXT

commands:
  sleepyhomes:
    description: Plugin info and reload command
    aliases: [sleepyhome]
    usage: /sleepyhomes <about|version|reload>
    permission: sleepyhomes.reload

  homes:
    description: Open the homes GUI
    usage: /homes

  home:
    description: Teleport to a home by number
    usage: /home <1-7>

  sethome:
    description: Automatically set your first available home slot
    usage: /sethome

  delhome:
    description: Delete a home by number
    usage: /delhome <1-7>

permissions:
  sleepyhomes.set.1:
    description: Access home slot 1 (view and set)
    default: false
  sleepyhomes.set.2:
    description: Access home slot 2
    default: false
  sleepyhomes.set.3:
    description: Access home slot 3
    default: false
  sleepyhomes.set.4:
    description: Access home slot 4
    default: false
  sleepyhomes.set.5:
    description: Access home slot 5
    default: false
  sleepyhomes.set.6:
    description: Access home slot 6
    default: false
  sleepyhomes.set.7:
    description: Access home slot 7
    default: false

  sleepyhomes.reload:
    description: Reload the plugin configuration at runtime
    default: op
